### ISSUE TITLE
Operation is not valid due to the current state of the object..

### ISSUE THREAD

**Issue by eneerge** [IdentityModel/Documentation#13]
I'm trying to use GetDiscoveryDocumentAsync(), but keep getting the following error:
"Error connecting to https://sts.windows.net/{tenant}/.well-known/openid-configuration. **Operation is not valid due to the current state of the object**

When using an older version that utilized Newtonsoft.JSON, I don't think this was an issue.

Here is the full stack trace:
`
 | StackTrace | "   at System.Text.Json.JsonElement.EnumerateObject()\r\n   at IdentityModel.Client.DiscoveryDocumentResponse.ValidateEndpoints(JsonElement json, DiscoveryPolicy policy)\r\n   at IdentityModel.Client.DiscoveryDocumentResponse.Validate(DiscoveryPolicy policy)\r\n   at IdentityModel.Client.DiscoveryDocumentResponse.InitializeAsync(Object initializationData)\r\n   at IdentityModel.Client.ProtocolResponse.<FromHttpResponseAsync>d__0``1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityModel.Client.HttpClientDiscoveryExtensions.<GetDiscoveryDocumentAsync>d__1.MoveNext()" | string
`

Here is the code I am using currently:
```
                var client = new System.Net.Http.HttpClient();

                DiscoveryDocumentRequest req = new DiscoveryDocumentRequest();

                DiscoveryPolicy pol = new DiscoveryPolicy();
                pol.ValidateIssuerName = false;
                pol.ValidateEndpoints = false;

                req.Policy = pol;
                //req.RequestUri = new Uri(m_authUri.AbsoluteUri);
                //client.BaseAddress = new Uri(m_authUri.AbsoluteUri);
                req.Address = m_authUri.AbsoluteUri;

                var disco = client.GetDiscoveryDocumentAsync(req);
                DiscoveryDocumentResponse discoveryResponse = disco.Result;
                if (discoveryResponse.IsError) // There is an exception message in discoveryResponse here.
                    throw new Exception("Failure discovering OpenID Settings", discoveryResponse.Exception);

```

This is the code I was using previously that worked without issue:
```
DiscoveryClient discoveryClient = new DiscoveryClient(m_authUri.AbsoluteUri);
discoveryClient.Policy.ValidateIssuerName = false;
discoveryClient.Policy.ValidateEndpoints = false;
var disco = discoveryClient.GetAsync().Result;
```

Worth mentioning that DiscoveryResponse.Raw is also empty, so it's like the request is not event sent.

![image](https://user-images.githubusercontent.com/7434613/126807225-a4684ff6-00b5-44c3-808a-cb5a458e8cbd.png)

**Comment by eneerge** [comment]
I managed to resolve this after uninstalling all NuGet packages and installing in a proper order. I must have broken something along the way.

After installing, I needed to add this to the web.config to fix a version conflict:
`	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="System.Text.Json" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-5.0.0.2" newVersion="5.0.0.2"/>
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0"/>
			</dependentAssembly>
		</assemblyBinding>
	</runtime>`

**Comment by Blamoh** [comment]
Worked for me, Thanks :)
