### ISSUE TITLE
Documentation on ReadTheDoc is not up to date

### ISSUE THREAD

**Issue by estradege** [IdentityModel/Documentation#17]
Hi, I saw there are some differences between doc on gitHub and readTheDoc, for example :

IDENTITYMODEL FOR WORKERS AND WEB > Worker Applications : 

The easiest way to register an HTTP client that uses the token management is by calling **AddClientAccessTokenClient**:

services.**AddClientAccessTokenClient**("client", configureClient: client =>
{
    client.BaseAddress = new Uri("https://demo.identityserver.io/api/");
});

The function is **AddClientAccessTokenHttpClient**. (ok on gitHub).

**Comment by leastprivilege** [comment]
Thanks for reporting! Please update it. Thanks.
